<?php

namespace Proxies\__CG__\Pfa\SistemaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AlumnoPago extends \Pfa\SistemaBundle\Entity\AlumnoPago implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Pfa\\SistemaBundle\\Entity\\AlumnoPago' . "\0" . 'id', '' . "\0" . 'Pfa\\SistemaBundle\\Entity\\AlumnoPago' . "\0" . 'idalumno', '' . "\0" . 'Pfa\\SistemaBundle\\Entity\\AlumnoPago' . "\0" . 'disciplina', '' . "\0" . 'Pfa\\SistemaBundle\\Entity\\AlumnoPago' . "\0" . 'precio', '' . "\0" . 'Pfa\\SistemaBundle\\Entity\\AlumnoPago' . "\0" . 'tipodepago', '' . "\0" . 'Pfa\\SistemaBundle\\Entity\\AlumnoPago' . "\0" . 'fechainicio', '' . "\0" . 'Pfa\\SistemaBundle\\Entity\\AlumnoPago' . "\0" . 'fechafinal', '' . "\0" . 'Pfa\\SistemaBundle\\Entity\\AlumnoPago' . "\0" . 'veces', '' . "\0" . 'Pfa\\SistemaBundle\\Entity\\AlumnoPago' . "\0" . 'vecestotales', '' . "\0" . 'Pfa\\SistemaBundle\\Entity\\AlumnoPago' . "\0" . 'vecesasistencia', 'lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo');
        }

        return array('__isInitialized__', '' . "\0" . 'Pfa\\SistemaBundle\\Entity\\AlumnoPago' . "\0" . 'id', '' . "\0" . 'Pfa\\SistemaBundle\\Entity\\AlumnoPago' . "\0" . 'idalumno', '' . "\0" . 'Pfa\\SistemaBundle\\Entity\\AlumnoPago' . "\0" . 'disciplina', '' . "\0" . 'Pfa\\SistemaBundle\\Entity\\AlumnoPago' . "\0" . 'precio', '' . "\0" . 'Pfa\\SistemaBundle\\Entity\\AlumnoPago' . "\0" . 'tipodepago', '' . "\0" . 'Pfa\\SistemaBundle\\Entity\\AlumnoPago' . "\0" . 'fechainicio', '' . "\0" . 'Pfa\\SistemaBundle\\Entity\\AlumnoPago' . "\0" . 'fechafinal', '' . "\0" . 'Pfa\\SistemaBundle\\Entity\\AlumnoPago' . "\0" . 'veces', '' . "\0" . 'Pfa\\SistemaBundle\\Entity\\AlumnoPago' . "\0" . 'vecestotales', '' . "\0" . 'Pfa\\SistemaBundle\\Entity\\AlumnoPago' . "\0" . 'vecesasistencia', 'lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AlumnoPago $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdalumno($idalumno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdalumno', array($idalumno));

        return parent::setIdalumno($idalumno);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdalumno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdalumno', array());

        return parent::getIdalumno();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisciplina($disciplina)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisciplina', array($disciplina));

        return parent::setDisciplina($disciplina);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisciplina()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisciplina', array());

        return parent::getDisciplina();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecio($precio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecio', array($precio));

        return parent::setPrecio($precio);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecio', array());

        return parent::getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipodepago($tipodepago)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipodepago', array($tipodepago));

        return parent::setTipodepago($tipodepago);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipodepago()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipodepago', array());

        return parent::getTipodepago();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechainicio($fechainicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechainicio', array($fechainicio));

        return parent::setFechainicio($fechainicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechainicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechainicio', array());

        return parent::getFechainicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechafinal($fechafinal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechafinal', array($fechafinal));

        return parent::setFechafinal($fechafinal);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechafinal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechafinal', array());

        return parent::getFechafinal();
    }

    /**
     * {@inheritDoc}
     */
    public function setVeces($veces)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVeces', array($veces));

        return parent::setVeces($veces);
    }

    /**
     * {@inheritDoc}
     */
    public function getVeces()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVeces', array());

        return parent::getVeces();
    }

    /**
     * {@inheritDoc}
     */
    public function setVecestotales($vecestotales)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVecestotales', array($vecestotales));

        return parent::setVecestotales($vecestotales);
    }

    /**
     * {@inheritDoc}
     */
    public function getVecestotales()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVecestotales', array());

        return parent::getVecestotales();
    }

    /**
     * {@inheritDoc}
     */
    public function setVecesasistencia($vecesasistencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVecesasistencia', array($vecesasistencia));

        return parent::setVecesasistencia($vecesasistencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getVecesasistencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVecesasistencia', array());

        return parent::getVecesasistencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setLunes($lunes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLunes', array($lunes));

        return parent::setLunes($lunes);
    }

    /**
     * {@inheritDoc}
     */
    public function getLunes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLunes', array());

        return parent::getLunes();
    }

    /**
     * {@inheritDoc}
     */
    public function setMartes($martes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMartes', array($martes));

        return parent::setMartes($martes);
    }

    /**
     * {@inheritDoc}
     */
    public function getMartes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMartes', array());

        return parent::getMartes();
    }

    /**
     * {@inheritDoc}
     */
    public function setMiercoles($miercoles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMiercoles', array($miercoles));

        return parent::setMiercoles($miercoles);
    }

    /**
     * {@inheritDoc}
     */
    public function getMiercoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMiercoles', array());

        return parent::getMiercoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setJueves($jueves)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJueves', array($jueves));

        return parent::setJueves($jueves);
    }

    /**
     * {@inheritDoc}
     */
    public function getJueves()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJueves', array());

        return parent::getJueves();
    }

    /**
     * {@inheritDoc}
     */
    public function setViernes($viernes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setViernes', array($viernes));

        return parent::setViernes($viernes);
    }

    /**
     * {@inheritDoc}
     */
    public function getViernes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getViernes', array());

        return parent::getViernes();
    }

    /**
     * {@inheritDoc}
     */
    public function setSabado($sabado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSabado', array($sabado));

        return parent::setSabado($sabado);
    }

    /**
     * {@inheritDoc}
     */
    public function getSabado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSabado', array());

        return parent::getSabado();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomingo($domingo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomingo', array($domingo));

        return parent::setDomingo($domingo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomingo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomingo', array());

        return parent::getDomingo();
    }

}
