<?php

namespace Proxies\__CG__\Pfa\SistemaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Box extends \Pfa\SistemaBundle\Entity\Box implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Pfa\\SistemaBundle\\Entity\\Box' . "\0" . 'id', 'fecha_inicio', 'precio', 'sexo', 'veces', 'idpago', 'lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo');
        }

        return array('__isInitialized__', '' . "\0" . 'Pfa\\SistemaBundle\\Entity\\Box' . "\0" . 'id', 'fecha_inicio', 'precio', 'sexo', 'veces', 'idpago', 'lunes', 'martes', 'miercoles', 'jueves', 'viernes', 'sabado', 'domingo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Box $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaInicio($fechaInicio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaInicio', array($fechaInicio));

        return parent::setFechaInicio($fechaInicio);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaInicio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaInicio', array());

        return parent::getFechaInicio();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecio($precio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecio', array($precio));

        return parent::setPrecio($precio);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecio', array());

        return parent::getPrecio();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexo($sexo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexo', array($sexo));

        return parent::setSexo($sexo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexo', array());

        return parent::getSexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setVeces($veces)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVeces', array($veces));

        return parent::setVeces($veces);
    }

    /**
     * {@inheritDoc}
     */
    public function getVeces()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVeces', array());

        return parent::getVeces();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdpago($idpago)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdpago', array($idpago));

        return parent::setIdpago($idpago);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdpago()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpago', array());

        return parent::getIdpago();
    }

    /**
     * {@inheritDoc}
     */
    public function setLunes($lunes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLunes', array($lunes));

        return parent::setLunes($lunes);
    }

    /**
     * {@inheritDoc}
     */
    public function getLunes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLunes', array());

        return parent::getLunes();
    }

    /**
     * {@inheritDoc}
     */
    public function setMartes($martes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMartes', array($martes));

        return parent::setMartes($martes);
    }

    /**
     * {@inheritDoc}
     */
    public function getMartes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMartes', array());

        return parent::getMartes();
    }

    /**
     * {@inheritDoc}
     */
    public function setMiercoles($miercoles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMiercoles', array($miercoles));

        return parent::setMiercoles($miercoles);
    }

    /**
     * {@inheritDoc}
     */
    public function getMiercoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMiercoles', array());

        return parent::getMiercoles();
    }

    /**
     * {@inheritDoc}
     */
    public function setJueves($jueves)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJueves', array($jueves));

        return parent::setJueves($jueves);
    }

    /**
     * {@inheritDoc}
     */
    public function getJueves()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJueves', array());

        return parent::getJueves();
    }

    /**
     * {@inheritDoc}
     */
    public function setViernes($viernes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setViernes', array($viernes));

        return parent::setViernes($viernes);
    }

    /**
     * {@inheritDoc}
     */
    public function getViernes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getViernes', array());

        return parent::getViernes();
    }

    /**
     * {@inheritDoc}
     */
    public function setSabado($sabado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSabado', array($sabado));

        return parent::setSabado($sabado);
    }

    /**
     * {@inheritDoc}
     */
    public function getSabado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSabado', array());

        return parent::getSabado();
    }

    /**
     * {@inheritDoc}
     */
    public function setDomingo($domingo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDomingo', array($domingo));

        return parent::setDomingo($domingo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDomingo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDomingo', array());

        return parent::getDomingo();
    }

}
